audien/urls.py
from django.conf.urls import patterns, include, url
from audien import views
from audien import models
from audien.forms import PerLetForm
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView 
from django.views.generic.edit import UpdateView 
from audien.forms import PerLetUpdateForm

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'projetoRAD.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
        
    url(r'^login/$','django.contrib.auth.views.login', name='login'),

    url(r'^logout/$','django.contrib.auth.views.logout',{'next_page': '/audien/login/'} ,name='logout'),

    url(r'^$', TemplateView.as_view(template_name='audien/index.html'), name='index'),
    
    url(r'^create_inst/$', CreateView.as_view(model=models.Instituicao, 
                        success_url='/audien/list_inst/'), name='create_inst'),
    
    url(r'^list_inst/$', ListView.as_view(model=models.Instituicao, paginate_by=3), name='list_inst'),
    
    url(r'^inst/(?P<pk>\d+)$', UpdateView.as_view(model=models.Instituicao,
                                                  template_name='audien/instituicao_update.html',
                                                  success_url='/audien/list_inst/'
                                                 ), name='update_inst'),

    url(r'^del_inst/(?P<pk>\d+)$', DeleteView.as_view(model=models.Instituicao,
                                                      success_url='/audien/list_inst/'),
                                   name='delete_inst'),

    url(r'^create_perlet/$', views.PerLetCreateView.as_view(model=models.PeriodoLetivo,
                                                form_class=PerLetForm,
                                                success_url='/audien/'), name='create_perlet'),


    url(r'^list_perlet/(?P<pk>\d+)$', views.PerLetView.as_view(model=models.PeriodoLetivo, paginate_by=5), name='list_perlet'),

    
    url(r'^del_perlet/(?P<pk>\d+)$', views.PerLetDeleteView.as_view(model=models.PeriodoLetivo), name='delete_perlet'),


    url(r'^perlet/(?P<pk>\d+)$', views.PerLetUpdateView.as_view(model=models.PeriodoLetivo,
                                                    form_class=PerLetUpdateForm,
                                                    template_name='audien/periodoletivo_update.html'), 
                                 name='update_perlet'),
    
    url(r'^mudar_perlet_atual/(?P<pk>\d+)$', views.mudarPeriodoAtual, name='mudarPeriodoAtual'),
    
    url(r'^create_estd/$', CreateView.as_view(model=models.Estudante, 
                                              success_url='/audien/list_estd',
                                              template_name_suffix='_create'), 
                           name='create_estd'),
    
    url(r'^list_estd/$', ListView.as_view(model=models.Estudante, paginate_by=5), name='list_estd'),
    
    url(r'^estd/(?P<pk>\d+)$', UpdateView.as_view(model=models.Estudante,
                                                  template_name='audien/estd_update.html',
                                                  success_url='/audien/list_estd/'
                                                 ), name='update_estd'),
    
    url(r'^del_estd/(?P<pk>\d+)$', DeleteView.as_view(model=models.Estudante,
                                                      success_url='/audien/list_estd/'),
                                   name='delete_estd'),


    url(r'^create_declara/(?P<pk>\d+)$', views.DeclaracaoCreateView.as_view(model=models.Declaracao, 
                                              success_url='/audien/list_estd',
                                              template_name_suffix='_create'), 
                           name='create_declara'),


    url(r'^list_declara/(?P<pk>\d+)$', views.DeclaracaoListView.as_view(model=models.Declaracao), name='list_declara'),

    url(r'^declara/(?P<pk>\d+)$', views.DeclaracaoUpdateView.as_view(model=models.Declaracao,
                                                  template_name='audien/declaracao_update.html'), 
                                  name='update_declara'),

    url(r'^del_declara/(?P<pk>\d+)$', views.DeclaracaoDeleteView.as_view(model=models.Declaracao),
                                      name='delete_declara'),

    
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
)

projetoRAD/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'projetoRAD.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^audien/', include('audien.urls', namespace='audien')),
)

audien/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
from django.core.validators import RegexValidator	
from django.contrib.auth.models import User
class Instituicao(models.Model):
	
	nome = models.CharField(max_length=80, unique=True, verbose_name='Nome')
	sigla = models.CharField(max_length=10, verbose_name='Sigla')
	fone = models.CharField(max_length=13, 
                                verbose_name='Fone', 
                                validators=[RegexValidator(r'\([1-9][1-9]\)[2-9][0-9]{3}-[0-9]{4}', 
                                                          "O formato é (XX)XXXX-XXXX")])	
	periodo_atual = models.OneToOneField('PeriodoLetivo', editable=False,null=True, related_name='perlet_atual',on_delete=models.SET_NULL)
	
	def mudarPeriodoAtual(self, pk):
		perlet = self.periodoletivo_set.get(pk=pk)
		perlet.save()
		self.save()


	def __unicode__(self):
		return self.sigla

	def save(self, *args, **kwargs):
		print 'Passa por aqui'
                if len(self.periodoletivo_set.all()) > 0:
                        print 'por aqui tbm!'
			self.periodo_atual = self.periodoletivo_set.all()[0]	
		super(Instituicao, self).save(*args, **kwargs)
	
	class Meta:
		ordering = ['-nome']
		verbose_name = 'Instituição'
		verbose_name_plural = 'Instituições'


class PeriodoLetivo(models.Model):
	
	PERIODOS = (
			(1, '1'), 
		   	(2, '2')
		   )
	
	ano = models.PositiveSmallIntegerField()
	periodo = models.PositiveSmallIntegerField(choices=PERIODOS, default=1)	
	inicio = models.DateField()
	fim = models.DateField()	
	instituicao = models.ForeignKey(Instituicao, verbose_name='Instituição')
	ultima_atualizacao = models.DateTimeField(editable=False, null=True, auto_now=True)	


	def __unicode__(self):
		return '%d.%d' % (self.ano, self.periodo) 

	class Meta:		
		
		ordering = ['-ultima_atualizacao']
		verbose_name = 'Período letivo'
		verbose_name_plural = 'Períodos Letivos'	
	
class Estudante(models.Model):
        
        nome = models.CharField(max_length=100, verbose_name='Nome')
        matricula = models.CharField(max_length=8, validators=[RegexValidator(r'\d{8}', 'Máximo de  8 números')],
                                     verbose_name='Matrícula', 
                                     unique=True)
        instituicaoAtual = models.ForeignKey(Instituicao, null=True, blank=True, 
                                            on_delete=models.SET_NULL, 
                                            verbose_name='Instituição Atual')

        def __unicode__(self):
            return self.nome
        
        class Meta:
                ordering = ['nome']
                verbose_name = 'Estudante'
                verbose_name_plural = 'Estudantes'

class Declaracao(models.Model):

    dataRecebimento = models.DateField(verbose_name='Data de Recebimento')
    observacao = models.CharField(max_length=100, verbose_name='Observação')
    estudante = models.ForeignKey(Estudante, verbose_name='Estudante')
    periodo_letivo = models.ForeignKey(PeriodoLetivo, verbose_name="Periodo Letivo")

    class Meta:
        ordering = ['-dataRecebimento']
        verbose_name = 'Declaração'
        verbose_name_plural = 'Declarações'

class UserProfile(models.Model):

    user = models.OneToOneField(User)

    email = models.EmailField()
    
    def __unicode__(self):
        return self.user.username

audien/forms.py
# -*- coding: utf-8 -*-
import sys

reload(sys)
sys.setdefaultencoding('utf-8')

from django import forms
from audien.models import Instituicao, PeriodoLetivo, UserProfile
from django.core.exceptions import ValidationError

class InstForm(forms.ModelForm):

    class Meta:
        model = Instituicao
        fields = ['nome', 'sigla', 'fone']


class PerLetForm(forms.ModelForm):
 
    """def is_valid(self):

        valid = super(PerLetForm, self).is_valid()

        if not valid:
            return valid

        try:
            inst = self.cleaned_data['instituicao']
            periodo_letivo = inst.periodoletivo_set.get(ano=self.cleaned_data['ano'],
                                                        periodo=self.cleaned_data['periodo'])

            self._errors['instituicao'] = u'Periodo Letivo já cadastrado nessa instituição'
            print self._errors
            return False
        except PeriodoLetivo.DoesNotExist:
            return True"""


    """def clean(self):
            try: 
                inst = self.cleaned_data.get('instituicao')
                periodo_letivo = inst.periodoletivo_set.get(ano=self.cleaned_data['ano'], 
                                                        periodo=self.cleaned_data['periodo'])
                raise ValidationError('Periodo Letivo já existe no(a) %s' % (inst.sigla))
            except PeriodoLetivo.DoesNotExist:
                return self.cleaned_data"""
	    
    def clean_instituicao(self):

	inst = self.cleaned_data.get('instituicao')
	
	try: 
	    periodo_letivo = inst.periodoletivo_set.get(ano=self.cleaned_data['ano'], 
						    periodo=self.cleaned_data['periodo'])
	    raise ValidationError('Periodo Letivo já existe nessa instituição')
	except PeriodoLetivo.DoesNotExist:
	    return inst 
    
    class Meta:
        model = PeriodoLetivo


class PerLetUpdateForm(forms.ModelForm):

    class Meta:
	model = PeriodoLetivo
	fields = ['ano', 'periodo', 'inicio', 'fim']

audien/views.py
# -*- coding: utf-8 -*-
import json
from audien import forms
from django.core.mail import  send_mail
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import UpdateView 
from audien.models import Instituicao, PeriodoLetivo, Estudante, Declaracao, UserProfile 
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView 
from django.core.urlresolvers import reverse
from django.views.generic.edit import UpdateView 
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django import forms
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class LoggedInMixin(object):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class PerLetView(LoggedInMixin, ListView):

    
    def get_queryset(self):
        inst = Instituicao.objects.get(pk=self.kwargs['pk'])
        objects = self.model.objects.filter(instituicao=inst).order_by('-pk')
        return objects


class PerLetDeleteView(LoggedInMixin, DeleteView):

    def get_object(self, queryset=None):
        perlet = super(PerLetDeleteView, self).get_object()
        self.success_url = reverse('audien:list_perlet', args=[perlet.instituicao.pk])
        return perlet

class PerLetUpdateView(LoggedInMixin, UpdateView):

    def get_success_url(self):
        
        perlet = super(PerLetUpdateView, self).get_object()
        return reverse('audien:list_perlet', args=[perlet.instituicao.pk])
       
class PerLetCreateView(SuccessMessageMixin, LoggedInMixin, CreateView):

    success_message = "Período Letivo cadastrado com sucesso!"
    
    def form_valid(self, form):
        
        perlet = form.save()
        
        perlet.instituicao.save()
        return super(PerLetCreateView, self).form_valid(form)
        
        

class DeclaracaoCreateView(SuccessMessageMixin, LoggedInMixin, CreateView):

    success_message = 'Declaração para %(nome_estd)s cadastrado com sucesso!'
    
    def get_form(self, form_class):
        
        if self.request.method == 'GET':    
            form = form_class(initial={'estudante': Estudante.objects.get(pk=self.kwargs['pk'])})
            inst = Estudante.objects.get(pk=self.kwargs['pk']).instituicaoAtual
            form.fields['periodo_letivo'].queryset=inst.periodoletivo_set.all()

            form.fields['estudante'].widget = forms.HiddenInput()
            return form
        elif self.request.method == 'POST':
            return super(DeclaracaoCreateView, self).get_form(form_class)

    def get_success_message(self, cleaned_data):
        
        nome_estd = Estudante.objects.get(pk=self.kwargs['pk']).nome
        return self.success_message % dict(cleaned_data,
                                           nome_estd=nome_estd)

class DeclaracaoListView(LoggedInMixin ,ListView):

    paginate_by = 3
    
    def get_queryset(self):
        declaracoes = Estudante.objects.get(pk=self.kwargs['pk']).declaracao_set.all()
        return declaracoes

    def get_context_data(self, **kwargs):
        estd = Estudante.objects.get(pk=self.kwargs['pk'])
        context = super(DeclaracaoListView, self).get_context_data(**kwargs)
        context['nome_estd'] = estd.nome.split(' ')[0] 
        return context

class DeclaracaoUpdateView(LoggedInMixin ,UpdateView):

    def get_form(self, form_class):
            form = super(DeclaracaoUpdateView, self).get_form(form_class)
            if self.request.method == 'GET': 
                form.fields['estudante'].widget = forms.HiddenInput()
                inst = Declaracao.objects.get(pk=self.kwargs['pk']).estudante.instituicaoAtual
                form.fields['periodo_letivo'].queryset=inst.periodoletivo_set.all()
            return form
    
    def get_success_url(self):
        
        estd = Declaracao.objects.get(pk=self.kwargs['pk']).estudante
        return reverse('audien:list_declara', args=[estd.pk]) 

class DeclaracaoDeleteView(LoggedInMixin ,DeleteView):

    def get_success_url(self):
        return reverse('audien:list_declara', args=[self.kwargs['pk']]) 

class SignUpView(SuccessMessageMixin, CreateView):
    model = UserProfile 
    template_name = 'audien/sign_up.html'
        
    success_url = "/audien/"
    success_message = 'Usuário cadastrado com sucesso! Um email foi enviado para sua caixa de email!'

    def form_valid(self, form):
        
        send_mail('Confirmação de cadastro', 
                  'Esse email confirma que vc se cadastrou no site.', 
                  'luheeslo@gmail.com', 
                  [form.instance.email], 
                  fail_silently=True)

        return super(SignUpView, self).form_valid(form)


@login_required
def mudarPeriodoAtual(request, pk):

    inst = PeriodoLetivo.objects.get(pk=pk).instituicao
    pk_perlet = inst.periodo_atual.pk
    inst.mudarPeriodoAtual(pk)
    if request.is_ajax():
        return HttpResponse(pk_perlet) 
    return redirect(reverse('audien:list_perlet', args=[inst.pk]))

templates/audien/base.html
{% load bootstrap3 %}
{% load static %}


{% bootstrap_css %}
<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>

<script src="{% static 'js/audien-ajax.js' %}"></script>
{% bootstrap_javascript %}

 <style>                                                                                                                                                     
     body {                                                                                                                                              
		 padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */                                                 
	 }
	
	 .principal{
		text-align: center; 
	 }
	 .form-control{
	 	width:'50%';
	 }

	 
	.form-signin {
        			max-width: 300px;
        			padding: 19px 29px 29px;
        			margin: 0 auto 20px;
        			background-color: #fff;
        			border: 1px solid #e5e5e5;
        			-webkit-border-radius: 5px;
           			-moz-border-radius: 5px;
                		border-radius: 5px;
        			-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           			-moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                		box-shadow: 0 1px 2px rgba(0,0,0,.05);
      			}
      			
	.form-signin .form-signin-heading,
      			.form-signin {
        			margin-bottom: 10px;
      			}
      			
	.form-signin input[type="text"],
		.form-signin input[type="password"] {
        			font-size: 16px;
        			height: auto;
        			margin-bottom: 15px;
        			padding: 7px 9px;
			}	
 </style>        

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'audien:index'%}">Audien</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
		  {% if user.is_anonymous %}
		  <li><a href="{% url 'audien:login' %}">Login</a></li>
		  <li><a href="{% url 'audien:signup' %}">Registro</a></li>
		  {% else %}	  
			 </li>
			 <li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Instituição<span class="caret"></span></a>
	            <ul class="dropdown-menu" role="menu">	
	            	<li><a href="{% url 'audien:create_inst' %}">Cadastrar</a></li>
	                <li><a href="{% url 'audien:list_inst' %}">Listar</a></li>
	            </ul>    
            </li>
            <li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Periodo Letivo<span class="caret"></span></a>
	        	<ul class="dropdown-menu" role="menu">	
					<li><a href="{% url 'audien:create_perlet' %}">Cadastrar</a></li>
            	</ul>
	        </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Estudantes<span class="caret"></span></a>
	        	<ul class="dropdown-menu" role="menu">	
					<li><a href="{% url 'audien:create_estd' %}">Cadastrar</a></li>
            		<li><a href="{% url 'audien:list_estd' %}">Listar</a></li>
            	</ul></li>

			</li>
			
			<li><a href="{% url 'audien:logout' %}">Logout</a></li>
			{% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</div>

{% bootstrap_messages %}

{% block principal %}{% endblock %}

templates/audien/declaracao_create.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{# bootstrap_messages #}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend>Cadastro de Declaração</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Cadastrar' reset="Cancelar"  layout="horizontal" %}
	{% endbuttons %}
</form>
{% endblock %}

templates/audien/declaracao_list.html
{% extends 'audien/base.html' %}

{% load bootstrap3 %}
{% block principal %}
<legend>Lista de Declarações de {{nome_estd}}</legend>
<table class="table">
	<tr>
		<th>Id</th>
		<th>Data de Recebimento</th>
		<th>Período Letivo</th>
	</tr>
	
		{% for declara in object_list %}
		<tr>
			<td><a href="{% url 'audien:update_declara' declara.pk %}">{{declara.pk }}</a></td>
			<td>{{ declara.dataRecebimento }}</td>
			<td>{{ declara.periodo_letivo }}</td>
		</tr>
		{% endfor %}
	</table>
	{% bootstrap_pagination page_obj url="?page={{ object_list.next_page_number }}" size="small" %}
{% endblock %}

templates/audien/declaracao_update.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{# bootstrap_messages #}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend>Atualizar Declaração</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Atualizar' reset="Limpar"  layout="horizontal" %}
		<button type="submit" class="btn btn-danger" formmethod="post"
			formaction="{% url 'audien:delete_declara' form.instance.pk %}" >Deletar</button> 
	{% endbuttons %}
</form>
{% endblock %}

templates/audien/estudante_list.html
{% extends 'audien/base.html' %}

{% load bootstrap3 %}
{% block principal %}
<legend>Lista de Estudantes</legend>
<table class="table">
	<tr>
		<th>Nome</th>
		<th>Instituição</th>
		<th></th>
		<th></th>
	</tr>
	
		{% for estudante in object_list %}
		<tr>
			<td><a href="{% url 'audien:update_estd' estudante.pk %}">{{ estudante }}</a></td>
			<td>{{ estudante.instituicaoAtual }}</td>
			<td><a href="{% url 'audien:create_declara' estudante.pk %}">Cadastrar Declaração</a></td>

			<td><a href="{% url 'audien:list_declara' estudante.pk %}">Ver Declarações</a></td>
		</tr>
		{% endfor %}	
	</table>


	{% bootstrap_pagination page_obj url="?page={{ object_list.next_page_number }}" size="small" %}
{% endblock %}

templates/audien/index.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{% block principal %}

<div class="container">
      <div class="principal">
        <h1>Audiente</h1>
        <p class="lead">Gerenciamento de declarações de estudantes</p>
      </div>
	  {% if not user.is_anonymous %}
	  		<p class="lead">Bem vindo, {{ user.username }}</p>
	  {% endif %}
	</div>
{% endblock %}

templates/audien/instituicao_form.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{% bootstrap_messages %}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend>Cadastro de Instituição</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Cadastrar' reset="Cancelar"  layout="horizontal" %}
	{% endbuttons %}
</form>
{% endblock %}

templates/audien/instituicao_list.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}

{% block principal %}
<legend>Lista de Instituições</legend>
<table class="table">
	<tr>
		<th>Nome</th>
		<th>Sigla</th>
		<th>Fone</th>
		<th>Periodos Letivos</th>
	</tr>
	
		{% for instituicao in object_list %}
		<tr>
			<td><a href="{% url 'audien:update_inst' instituicao.pk %}">{{ instituicao.nome }}</a></td>
			<td>{{ instituicao.sigla }}</td>
			<td>{{ instituicao.fone }}</td>
			<td><a href="{% url 'audien:list_perlet' instituicao.pk %}">Ver Periodos Letivos</a></td>
		</tr>
		{% endfor %}	
	</table>
	{% bootstrap_pagination page_obj url="?page={{ object_list.next_page_number }}" size="small" %}
	
{% endblock %}

templates/audien/instituicao_update.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{% bootstrap_messages %}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	{{ pk }}
	<legend>Atualizar Dados da  Instituição</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Atualizar' reset="Limpar"  layout="horizontal" %}
		<button type="submit" class="btn btn-danger" formmethod="post" formaction="{% url 'audien:delete_inst' form.instance.pk %}" >Deletar</button> 
	{% endbuttons %}
</form>
{% endblock %}

templates/audien/logged_out.html
{% extends "audien/base.html" %}

{% block principal %}
Logged out!
{% endblock %}

templates/audien/periodoletivo_form.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{# bootstrap_messages #}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend>Cadastro de Periodo Letivo</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Cadastrar' reset="Cancelar"  layout="horizontal" %}
	{% endbuttons %}
</form>
{% endblock %}

templates/audien/periodoletivo_list.html
{% extends 'audien/base.html' %}

{% load bootstrap3 %}

{% block principal %}
<legend>Lista de Periodos da(o) {{ object_list.0.instituicao }}</legend>
<table class="table">
	<tr>
		<th>Semestre</th>
		<th>Início</th>
		<th>Fim</th>
		<th>Periodo Atual?</th>
	</tr>
	
		{% for perlet in object_list %}
		<tr>
			<td><a href="{% url 'audien:update_perlet' perlet.pk %}">{{ perlet }}</a></td>
			<td>{{ perlet.inicio }}</td>
			<td>{{ perlet.fim }}</td>
			<td>
				
				<a class="mudar_perlet" data-perletid={{ perlet.pk }}>
				{% if perlet.instituicao.periodo_atual == perlet %}
					<span class="glyphicon glyphicon-star"></span>
				{% else %}
					<span class="glyphicon glyphicon-star-empty"></span>
				{% endif %}

			    </a>	
			</td>

		</tr>
		{% endfor %}	
	</table>
	{% bootstrap_pagination page_obj url="?page={{ object_list.next_page_number }}" size="small" %}
{% endblock %}

templates/audien/periodoletivo_update.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{# bootstrap_messages #}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend>Cadastro de Periodo Letivo</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Atualizar' reset="Limpar"  layout="horizontal" %}
		<button type="submit" class="btn btn-danger" formmethod="post"
			formaction="{% url 'audien:delete_perlet' form.instance.pk %}" >Deletar</button> 
	{% endbuttons %}
</form>
{% endblock %}

templates/audien/sign_up.html
{% extends 'audien/base.html' %}
{% load bootstrap3 %}
{# bootstrap_messages #}
{% block principal %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend>Cadastro de Usuário</legend>
	{% bootstrap_form form layout="horizontal" %}
	{% buttons submit='Cadastrar' reset="Cancelar"  layout="horizontal" %}
	{% endbuttons %}
</form>
{% endblock %}